sudo: false
cache:
  directories:
    - $HOME/.cache/pip

language: python

matrix:
  include:
    - python: "pypy3"
      env: TOXENV=pypy3
    - python: "3.6"
      env: TOXENV=py36
    - python: "3.7"
      env: TOXENV=py37
      dist: xenial
      sudo: true

    # Prevent breakage on new releases
    - python: "3.6-dev"
      env: TOXENV=py36
    - python: "3.7-dev"
      env: TOXENV=py37

    # Meta
    - python: "3.6"
      env: TOXENV=lint
    - python: "3.6"
      env: TOXENV=docs

allow_failures:
  - python: "3.6-dev"
  - python: "3.7-dev"

install:
  - pip install tox

script:
  - tox

before_install:
  - pip install codecov

after_success:
  - tox -e coverage-report
  - codecov

notifications:
  email: false
