dist: xenial
cache:
  directories:
    - $HOME/.cache/pip

language: python

matrix:
  fast_finish: true

  include:
    - python: "3.6"
      env: TOXENV=py3
    - python: "3.7"
      env: TOXENV=py3

    # Prevent breakage on new releases
    - python: "3.6-dev"
      env: TOXENV=py3
    - python: "3.7-dev"
      env: TOXENV=py3
    - python: "3.8-dev"
      env: TOXENV=py3

    # Meta
    - python: "3.7"
      env: TOXENV=lint
    - python: "3.7"
      env: TOXENV=docs

allow_failures:
  - python: "3.6-dev"
  - python: "3.7-dev"
  - python: "3.8-dev"

install:
  - pip install -U tox

script:
  - tox

before_install:
  - pip install codecov

after_success:
  - tox -e coverage-report
  - codecov

notifications:
  email: false
